apiVersion: v1
kind: Service
metadata:
  name: {{ include "unnamed.fullname" . }}
  labels:
    {{- include "unnamed.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector: {{ include "unnamed.selectorLabels" . | nindent 4 }}
